In [1]:
l = [23444, 34, 422, 322, -3442]

In [2]:
l

[23444, 34, 422, 322, -3442]

In [3]:
import numpy as np

In [5]:
a = np.array(l)

In [6]:
a

array([23444,    34,   422,   322, -3442])

In [7]:
b = np.array([12, 455, 63.3, True, 'abc'])

In [8]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [9]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [10]:
l.pop()

-3442

In [11]:
l

[23444, 34, 422, 322]

In [12]:
a.mean()

4156.0

In [21]:
c = np.array([True, False, True, 5])

In [22]:
c

array([1, 0, 1, 5])

In [23]:
d = np.array(['what', 12])

In [25]:
d

array(['what', '12'], dtype='<U4')

In [27]:
l[1:]

[34, 422, 322]

In [29]:
l[0:2]

[23444, 34]

In [30]:
l[::2]

[23444, 422]

---

In [31]:
a

array([23444,    34,   422,   322, -3442])

In [32]:
a[2:]

array([  422,   322, -3442])

In [33]:
a[2:4]

array([422, 322])

In [34]:
b = a[2:4]

In [35]:
b

array([422, 322])

In [36]:
b[0]

422

In [39]:
b[:] = 111

In [40]:
b

array([111, 111])

In [41]:
a

array([23444,    34,   111,   111, -3442])

In [42]:
c = a.copy()

In [43]:
c[0] = 0

In [44]:
c

array([    0,    34,   111,   111, -3442])